### ISSUE TITLE
I think FlashAttention 2 ROCM support is upstreamed?

### ISSUE THREAD

**Issue by FeepingCreature** [Beinsezii/comfyui-amd-go-fast#4]
https://github.com/Dao-AILab/flash-attention/pull/1010

ROCM branch seems to? no longer be necessary to use this.

Though you need to have `FLASH_ATTENTION_TRITON_AMD_ENABLE=TRUE` set.

And as far as I can tell - sadly - on my 7900 XTX your wheels from [here](https://github.com/Beinsezii/comfyui-amd-go-fast/issues/2#issuecomment-2103639275) are *considerably* faster than whatever this is. (3it/s vs 4it/s approximately)

Might be worth to look into what they're doing different, as the howiejay branch is p much dead it seems.

**Comment by Beinsezii** [comment]
The howiejay branch uses native HIP kernels instead of Triton. Triton isn't very optimized for GFX11 yet so it's not going to be faster. You could try triton nightly or something see if it's any better.

**Comment by FeepingCreature** [comment]
Yeah I guess. AMD why do you do these things.

**Comment by Beinsezii** [comment]
yeah rocm support is weak enough if this card wasn't so good for games I would've sold it

**Comment by Beinsezii** [comment]
More bad news is it seems like proper CK flash support for navi31 is sill a ways off
https://github.com/pytorch/pytorch/pull/138947#discussion_r1884680252
Only been what over a year and that branch howiejay made in a weekend is still the best we have.

**Comment by FeepingCreature** [comment]
However, Pytorch Nightly no longer seems to spew out a giant flood of compile errors when you invoke the TorchCompileModel node, and with Pytorch cross attention and the TorchCompileModel node active, 1024x1024 sdxl speed is for the first time competetive with howiejay!

**Comment by Beinsezii** [comment]
Yeah the howiejay attention causes graph breaks so it can't be used with compile. You might even be able to beat it with torchao now that nightly uses the blaslt backend which supports int8 I think.

The other PR I'm curious about is https://github.com/pytorch/pytorch/pull/143971

but this quote https://github.com/pytorch/pytorch/pull/143971#issuecomment-2569594821

is wild and makes me worried about their development tbh.

**Comment by FeepingCreature** [comment]
Yeah what the heck. I simply don't understand how nobody at AMD can get *a thousand bucks* together to get the people making the primary ML framework a single working card. Completely bonkers.

**Comment by FeepingCreature** [comment]
Especially because it's a PR from AMD and they've clearly not run the testsuite either!

**Comment by FeepingCreature** [comment]
Well that was nice while it lasted. `torch.compile` doesn't work anymore, even if I go back to regular nightly.

**Comment by Beinsezii** [comment]
Torch.compile always works for me in diffusers back to torch 2.2 or 2.3 I think. It might be an issue with whatever flags they're passing to the node.

**Comment by FeepingCreature** [comment]
I figured out how to get it to work again. (I had the wrong triton installed lol)

Current state:

- torch.compiled ck backend from PR: 4.33it/s, 5.38s
- torch.compiled PR without ck backend (hipblaslt presumably): 4.07it/s, 5.68s
- torch.compiled amd go fast: graph break, no benefit
- amd go fast without torch.compile: 4.34it/s, 5.33s

howiejay fucking cooked fr.

**Comment by jnolck** [comment]
> Yeah the howiejay attention causes graph breaks so it can't be used with compile. You might even be able to beat it with torchao now that nightly uses the blaslt backend which supports int8 I think.
> 
> The other PR I'm curious about is [pytorch/pytorch#143971](https://github.com/pytorch/pytorch/pull/143971)
> 
> but this quote [pytorch/pytorch#143971 (comment)](https://github.com/pytorch/pytorch/pull/143971#issuecomment-2569594821)
> 
> is wild and makes me worried about their development tbh. I would love for the day when I can archive this repo because upstream is finally able to match or best it but 11 months in and seeing their most popular consumer ML sku having PRs stalled because they don't provide infrastructure to test it makes me feel like this repository will be up well passed the GFX12 release...

I came here to share that, but you beat me to it. It's still a little bit slower, but I have no issue compiling models with it, so the combo of flash attention + torch.compile + tunableops ends up being a little bit faster overall. The reason I looked into trying the triton based flash attention is because I noticed ck based implementation was very slow in the 2.7 nightly's. 

Has anyone tried using the migraphx backend in torch.compile? https://github.com/ROCm/torch_migraphx. I can't try it because I'm on fedora and there's no migraphx package for it yet.

**Comment by Beinsezii** [comment]
>  I can't try it because I'm on fedora and there's no migraphx package for it yet.

Fedora comes with podman preconfigured so you can easily make an ubuntu image using the official packages to overlay with https://github.com/89luca89/distrobox

> Has anyone tried using the migraphx backend in torch.compile? https://github.com/ROCm/torch_migraphx.

No, but I suppose I can...

|method|tunable|sdxl|
|-|-|-|
|sdpa|false|3.45|
|sdpa|true|3.63|
|ckflash|false|3.89|
|ckflash|true|4.10|
|compile|false|3.67|
|compile|true|4.20|
|migraphx|false|NaN|
|migraphx|true|NaN|

...but migraphx threw a runtime error for not supporting the shapes sdxl needed to run.

**Comment by jnolck** [comment]
> > I can't try it because I'm on fedora and there's no migraphx package for it yet.
> 
> Fedora comes with podman preconfigured so you can easily make an ubuntu image using the official packages to overlay with https://github.com/89luca89/distrobox
> 
> > Has anyone tried using the migraphx backend in torch.compile? https://github.com/ROCm/torch_migraphx.
> 
> No, but I suppose I can...
> method 	tunable 	sdxl
> sdpa 	false 	3.45
> sdpa 	true 	3.63
> ckflash 	false 	3.89
> ckflash 	true 	4.10
> compile 	false 	3.67
> compile 	true 	4.20
> migraphx 	false 	NaN
> migraphx 	true 	NaN
> 
> ...but after a minute of compiling migraphx threw a runtime error for not supporting the shapes sdxl needed to run.

LOL. I'm so old school. I had no idea about the whole container thing, so I've obsessed over it for the last couple of days. Got a Ubuntu image installed and the official rocm package installed inside. Thank you for that tip. I think I might change up my whole setup due to this. It's so clean. 

I got migraphx working inside comfyui. Had the alter the confy node with the compile node I'm using. It's WaveSpeed in my case. Just a one liner. import torch_migraphx, then set the backend to migraphx instead of inductor. It was a bust. It took forever to compile and it was slower then the default inductor back-end. The output was not good either. Probably buggy. 

I'm not sure if it's a bug or if I'm not understanding the whole concept, but the inductor back-end is slower with the max-autotune option. It takes a long time to compile and when it's done generation time is either a bit slow or the same speed as when compiling without the option. 

Tested migraphx with max-autotune. Crashed with out of memory error. Sigh. 

I'll test inductor with max-autotune and the ck backend. 

Kinda of bummed out about it. I thought I would be able to squeeze some more performance out of this card with that. So using composoble kernel didn't make pytorch faster, neither did migraphx.

**Comment by Beinsezii** [comment]
At this point I think any other gains will be fighting for table scraps until there's some major gfx11 kernel reworking from AMD in either torch or triton. Superficially it seems like all the optimization has gone into gfx942 outside of the triton flash which is okayish on gfx11. To give you an idea, I have a remote 4090 through work and it's something like 8.5 it/s without any compile or tunable or anything. The disparity is even worse for fat models like Flux.

**Comment by Beinsezii** [comment]
I re-ran the same benchmarks on a 4090 for posterity and interestingly it doesn't seem to benefit from tunable. The table is still created but I'm assuming its just already optimized or it doesn't support any tunable parameters that speed up sdxl

|method|tunable|sdxl|
|-|-|-|
|sdpa|false|8.67|
|sdpa|true|8.67|
|compile|false|9.23|
|compile|true|9.23|

Obviously the XTX is a smaller GPU with even less wmma's but still I think we should at least be more than ⅖ the speed...

**Comment by feffy380** [comment]
> I figured out how to get it to work again. (I had the wrong triton installed I think?)
> 
> Current state:
> 
>     * torch.compiled ck backend from PR (ie. wmma for fp16): 4.33it/s, 5.38s
> 
>     * torch.compiled PR without ck backend (hipblaslt presumably): 4.07it/s, 5.68s
> 
>     * torch.compiled amd go fast: graph break, no benefit
> 
>     * amd go fast without torch.compile: 4.34it/s, 5.33s

Does the ck backend support backward pass?

**Comment by FeepingCreature** [comment]
To be fair theeeeeeeoretically doesn't the 4090 have 3x the fp16 tflops of the 7900 xtx?

**Comment by Beinsezii** [comment]
> Does the ck backend support backward pass?

Try it and find out. Then you can let us know.

> To be fair theeeeeeeoretically doesn't the 4090 have 3x the fp16 tflops of the 7900 xtx?

I really doubt it's anywhere near that in practice unless the difference in wmma's is that extreme. Somewhere buried in I think the Flash Attention repo is some AMD engineers discussing which card to benchmark the XTX against and they started with the 4090 before switching to the 3090 Ti I think.
